jobs: 
  - job: build
    # pool:
    #     vmImage: 'windows-latest'
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET Core SDK'
        inputs:
          version: 6.x
          performMultiLevelLookup: true
          includePreviewVersions: true # Required for preview versions

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
        
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build ${{ parameters.buildConfiguration}}'
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration ${{ parameters.buildConfiguration}}'

      - task: DotNetCoreCLI@2
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration ${{ parameters.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: True

      # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)' 
          artifactName: ${{ parameters.ArtifactName }} 