trigger: 
  - main

variables:
  - name: task
    value: "Test Pipeline tasks:"

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Stage1
    jobs:
      - job: Job1
        steps:
          - script: echo Hello, $(task)
            displayName: 'Run a one-line script'         
          
          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Run a multi-line script'

          - task: Bash@3
            displayName: 'Bash Task: Run a Bash script on macOS, Linux, or Windows.'
            inputs:
              targetType: inline
              script: |
                echo "Bash task: Test" 
    
      - job: Job2
        steps:
          - task: PowerShell@2
            displayName: 'PowerShell Task: Run inline Powershell command'
            inputs:
              targetType: 'inline'
              script: Write-Host "##vso[task.LogIssue type=warning;]This is the warning"
              # Writes a warning to build summary and to log in yellow text   

  - stage: Stage2
    jobs:
      - job: Job1
        steps:
          - task: CmdLine@2
            displayName: "CmdLine Task: Run a command line script using Bash on Linux and macOS and cmd.exe on Windows."
            inputs:
              script: |         
                echo "Build.ArtifactStagingDirectory:" 
                echo "$(Build.ArtifactStagingDirectory)"
      
                echo "Build.BinariesDirectory:" 
                echo "$(Build.BinariesDirectory)"
      
                echo "Build.SourcesDirectory:"
                echo "$(Build.SourcesDirectory)"

                echo  "System.DefaultWorkingDirectory:"
                echo  "$(System.DefaultWorkingDirectory)"

                echo  "Pipeline.Workspace:"
                echo  "$(Pipeline.Workspace)"

                echo "Structure of work folder of this pipeline:"
                tree $(Agent.WorkFolder)/1

      - job: Job2
        steps:    
          - task: CopyFiles@2
            displayName: 'Copy Files'
            inputs:
              contents: 'Pipelines/Templates/PowerShell/test.ps1'
              targetFolder: $(Build.ArtifactStagingDirectory)

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifacts'
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: 'scriptfile'

          - task: PowerShell@2
            displayName: 'PowerShell Task: Run scripts from file'
            inputs:
              targetType: 'filePath'
              filePath: 'Pipelines/Templates/PowerShell/test.ps1'

          - task: PowerShell@2
            displayName: List all folders in $(Pipeline.Workspace)
            inputs:
              targetType: 'inline'
              script: |
                Get-ChildItem - path $(Pipeline.Workspace)

    # Download an artifact named 'scriptfile' to ps folder in $(Build.SourcesDirectory)
      - job: Job3
        # dependsOn: Job2
        steps:  
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Artifact'
            inputs:
              artifactName: 'scriptfile'
              targetPath: $(Build.SourcesDirectory)/ps
          
          - task: CmdLine@2
            displayName: "CmdLine Task: Run a command line script using Bash on Linux and macOS and cmd.exe on Windows."
            inputs:
              script: |   
                echo "Structure of work folder of this pipeline:"
                tree $(Agent.WorkFolder)/1