trigger: 
  - none

variables:
  - name: task
    value: "Test Pipeline tasks:"

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Stage1
    jobs:
      - job: Job1
        steps:
          - script: echo Hello, $(task)
            displayName: 'Run a one-line script'   

  - stage: Stage2
    jobs:
      - job: Job1
        steps:
          - task: CmdLine@2
            displayName: "CmdLine Task: Run a command line script using Bash on Linux and macOS and cmd.exe on Windows."
            inputs:
              script: | 
                echo "Structure of work folder of this pipeline:"
                tree $(Agent.WorkFolder)/1
                cat Pipelines/Templates/PowerShell/test.ps1