trigger: 
  - main

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

variables:      # pipeline-level
  var1: 'pipeline-level'

stages:
  - stage: Stage1
    variables:    # stage-level
    var2: 'stage1-var'
    jobs:
      - job: Job1
        variables:  # job-level
        var2: 'job1-var'
        steps:
          - script: echo Hello, $(var2)
            displayName: 'print var2'   

  - stage: Stage2
    variables:    # stage-level
    var3: 'stage2-var'
    jobs:
      - job: Job1
        steps:
          - script: echo Hello, $(var3)
            displayName: 'print var3'

  - stage: Stage3
    jobs:
      - job: Job1
        variables:    # job-level
        var4: 'Stage3-job1-var'
        steps:
          - script: echo Hello, $(var4)
            displayName: 'print var4'

      - job: Job2
        steps:
          - task: CmdLine@2
            displayName: "CmdLine Task: Run a command line script using Bash on Linux and macOS and cmd.exe on Windows."
            inputs:
              script: |         
                echo "Build.ArtifactStagingDirectory:" 
                echo "$(Build.ArtifactStagingDirectory)"
      
                echo "Build.BinariesDirectory:" 
                echo "$(Build.BinariesDirectory)"
      
                echo "Build.SourcesDirectory:"
                echo "$(Build.SourcesDirectory)"

                echo  "System.DefaultWorkingDirectory:"
                echo  "$(System.DefaultWorkingDirectory)"

                echo  "Pipeline.Workspace:"
                echo  "$(Pipeline.Workspace)"

                echo "Structure of work folder of this pipeline:"
                tree $(Agent.WorkFolder)/1   