trigger: 
  - main

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest


# pipeline-level
variables:
- name: var1                    # name of a variable
  value: 'pipeline-level var1'       # value of the variable
- name: var2                    # name of a variable
  value: 'pipeline-level var2'       # value of the variable

- group: webapp-variables       # name of a variable group
- template: Pipelines\Variables\build.yaml  # template reference


stages:
  - stage: Stage1
    variables:    # stage-level
      var1: 'stage1-var'
    jobs:
      - job: Job1
        variables:  # job-level
          var1: 'job1-var'
        steps:        
          - script: |
              displayName: 'print var1'  
              echo Hello, $(var1)
              echo Hello, $(var2)

              echo Hello, $(DeploymentName) 
              echo Hello, $(Environment)  

              echo Hello, $(config)  
              echo Hello, $(vmImage)  
                        

  - stage: Stage2
    variables:    # stage-level
      var1: 'stage2-var'
    jobs:
      - job: Job1
        steps:
          - script: echo Hello, $(var1)
            displayName: 'print var1'

  - stage: Stage3
    jobs:
      - job: Job1
        steps:
          - script: echo Hello, $(var1)
            displayName: 'print var1'

      - job: Job2
        steps:
          - task: CmdLine@2
            displayName: "CmdLine Task: Run a command line script using Bash on Linux and macOS and cmd.exe on Windows."
            inputs:
              script: |         
                echo "Build.ArtifactStagingDirectory:" 
                echo "$(Build.ArtifactStagingDirectory)"
      
                echo "Build.BinariesDirectory:" 
                echo "$(Build.BinariesDirectory)"
      
                echo "Build.SourcesDirectory:"
                echo "$(Build.SourcesDirectory)"

                echo  "System.DefaultWorkingDirectory:"
                echo  "$(System.DefaultWorkingDirectory)"

                echo  "Pipeline.Workspace:"
                echo  "$(Pipeline.Workspace)"

                echo "Structure of work folder of this pipeline:"
                tree $(Agent.WorkFolder)/1   