trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- name: buildConfiguration
  value: 'Release'
- group: webapp-variables            


stages:
  - stage: Build
    jobs: 
      - template: Templates/build.yaml
        parameters: buildConfiguration ${{ variables.buildConfiguration }}
        

  # - stage: Deploy
  #   jobs: 
  #   - job:
  #     steps:
  #       # download the artifact drop from the previous job
  #       - task: DownloadPipelineArtifact@2
  #         inputs:
  #           source: 'current'
  #           artifact: 'webappartifact'
  #           path: '$(Pipeline.Workspace)'

  #       - task: AzureWebApp@1
  #         inputs:
  #           azureSubscription: $(ServiceConnection)
  #           appType: 'webApp'
  #           appName: 'samplewebapp89'
  #           resourceGroupName: 'test-rg'
  #           package: '$(Pipeline.Workspace)/**/*.zip'