parameters:
  - name: environment
    displayName: Select Environment to deploy?
    type: string
    default: 'dev'
    values:
    - dev
    - test
    - prd
 
stages:
- stage: TaskSelected
  jobs:
  - job: colour
    steps:
      - ${{ if eq( parameters['environment'], 'dev') }}:
        - task: Bash@3
          displayName: task1
          inputs:
            targetType: inline
            script: |
              echo "task1 is used as environment: ${{parameters.environment}} was selected"

      - ${{ elseif eq( parameters['environment'], 'test') }}:
        - task: Bash@3
          displayName: task2
          inputs:
            targetType: inline
            script: |
              echo "task2 is used as environment: ${{parameters.environment}} was selected"

      - ${{ else }}:
        - task: Bash@3
          displayName: task3
          inputs:
            targetType: inline
            script: |
              echo "task3 is used as environment: ${{parameters.environment}} was selected"
