trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  pipelines: 
   pipeline: parent
  source: parent
  trigger:
    stages:
      - child2   

stages:
- stage: 'child2'
  jobs:
  - job:
      steps:        
          script: echo "In child2 pipeline"