trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  pipelines: 
   pipeline: parent
  source: parent
  trigger:
    stages:
      - child1    

stages:
- stage: 'child1'
  jobs:
  - job:
      steps:        
          script: echo "In child1 pipeline"