trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  pipelines: 
   pipeline: parent
  source: parent
  trigger:
    stages:
      - child3    

stages:
- stage: 'child3'
  jobs:
  - job:
      steps:        
          script: echo "In child3 pipeline"